// src/ui/history-v3/src/components/message/SystemMessage.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { SystemBlock } from '@/types'
import { useFormatters } from '@/composables/useFormatters'
import { useCopyToClipboard } from '@/composables/useCopyToClipboard'
import BaseBadge from '@/components/ui/BaseBadge.vue'
import IconSvg from '@/components/ui/IconSvg.vue'
import RawJsonModal from '@/components/ui/RawJsonModal.vue'
import DiffView from './DiffView.vue'

const props = defineProps<{
  system: string | SystemBlock[]
  rewrittenSystem?: string | SystemBlock[] | null
  searchQuery?: string
}>()

const { highlightSearch, escapeHtml } = useFormatters()
const { copy } = useCopyToClipboard()

const collapsed = ref(false)
const expanded = ref(false)
const viewMode = ref<'original' | 'rewritten' | 'diff'>('original')
const showRawModal = ref(false)

function systemToText(system: string | SystemBlock[]): string {
  if (typeof system === 'string') return system
  if (Array.isArray(system)) return system.map(b => b.text).join('\n')
  return ''
}

const originalText = computed(() => systemToText(props.system))
const rewrittenText = computed(() => props.rewrittenSystem ? systemToText(props.rewrittenSystem) : '')
const hasRewrite = computed(() => !!props.rewrittenSystem)

const displayText = computed(() => {
  if (viewMode.value === 'rewritten' && hasRewrite.value) return rewrittenText.value
  return originalText.value
})

const displayHtml = computed(() => {
  if (props.searchQuery) return highlightSearch(displayText.value, props.searchQuery)
  return escapeHtml(displayText.value)
})

const summary = computed(() => {
  const t = originalText.value
  return t.length > 80 ? t.slice(0, 80) + '...' : t
})

const systemBlocks = computed<SystemBlock[]>(() => {
  if (typeof props.system === 'string') return [{ type: 'text', text: props.system }]
  return props.system
})

const hasCacheControl = computed(() => {
  if (typeof props.system === 'string') return false
  return props.system.some(b => b.cache_control)
})

const rawData = computed(() => {
  return { system: props.system, rewrittenSystem: props.rewrittenSystem }
})
</script>

<template>
  <div class="system-message" :class="{ collapsed }">
    <div class="system-header" @click="collapsed = !collapsed">
      <div class="system-header-left">
        <span class="collapse-icon">{{ collapsed ? '▸' : '▾' }}</span>
        <BaseBadge color="purple">system</BaseBadge>
        <BaseBadge v-if="hasCacheControl" color="warning">cached</BaseBadge>
        <BaseBadge v-if="hasRewrite" color="warning">rewritten</BaseBadge>
        <span v-if="collapsed" class="collapsed-summary">{{ summary }}</span>
      </div>

      <div class="system-header-right">
        <!-- Rewrite view toggle -->
        <div v-if="hasRewrite && !collapsed" class="view-toggle" @click.stop>
          <button :class="{ active: viewMode === 'original' }" @click="viewMode = 'original'">Original</button>
          <button :class="{ active: viewMode === 'rewritten' }" @click="viewMode = 'rewritten'">Rewritten</button>
          <button :class="{ active: viewMode === 'diff' }" @click="viewMode = 'diff'">Diff</button>
        </div>

        <button v-if="!collapsed" class="action-btn" @click.stop="expanded = !expanded" v-show="!expanded">
          <IconSvg name="expand" :size="10" />
          Expand
        </button>
        <button v-if="!collapsed && expanded" class="action-btn" @click.stop="expanded = false">
          <IconSvg name="contract" :size="10" />
          Collapse
        </button>

        <button class="action-btn" title="Copy" @click.stop="copy(displayText)">
          <IconSvg name="copy" :size="10" />
          Copy
        </button>
        <button class="action-btn" title="View raw JSON" @click.stop="showRawModal = true">
          <IconSvg name="code" :size="10" />
          Raw
        </button>
      </div>
    </div>

    <div v-show="!collapsed" class="system-body" :class="{ 'body-expanded': expanded }">
      <DiffView
        v-if="viewMode === 'diff' && hasRewrite"
        :old-text="originalText"
        :new-text="rewrittenText"
      />
      <template v-else-if="viewMode === 'original' && typeof system !== 'string'">
        <div v-for="(block, i) in systemBlocks" :key="i" class="system-block-item">
          <div v-if="block.cache_control" class="cache-label">[cache: {{ block.cache_control.type }}]</div>
          <pre class="system-text" v-html="searchQuery ? highlightSearch(block.text, searchQuery) : escapeHtml(block.text)" />
        </div>
      </template>
      <pre v-else class="system-text" v-html="displayHtml" />
    </div>

    <RawJsonModal
      :visible="showRawModal"
      title="Raw — system"
      :data="rawData"
      @update:visible="showRawModal = $event"
    />
  </div>
</template>

<style scoped>
.system-message {
  border: 1px solid rgba(163, 113, 247, 0.3);
  overflow: hidden;
  margin-bottom: var(--spacing-sm);
}

.system-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--spacing-xs) var(--spacing-sm);
  background: var(--purple-muted);
  cursor: pointer;
  user-select: none;
}

.system-header:hover {
  background: rgba(163, 113, 247, 0.2);
}

.system-header-left {
  display: flex;
  align-items: center;
  gap: var(--spacing-xs);
  min-width: 0;
  overflow: hidden;
}

.collapse-icon {
  font-size: 10px;
  color: var(--text-dim);
  width: 10px;
  flex-shrink: 0;
}

.collapsed-summary {
  font-size: var(--font-size-xs);
  color: var(--text-dim);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.system-header-right {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

.view-toggle {
  display: flex;
  gap: 1px;
  background: var(--bg);
  overflow: hidden;
}

.view-toggle button {
  font-size: var(--font-size-xs);
  padding: 2px 8px;
  color: var(--text-muted);
  background: var(--bg-secondary);
}

.view-toggle button:hover {
  color: var(--text);
}

.view-toggle button.active {
  color: var(--primary);
  background: var(--primary-muted);
}

.action-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: var(--font-size-xs);
  color: var(--text-dim);
  padding: 2px 6px;
  background: transparent;
}

.action-btn:hover {
  color: var(--text);
  background: var(--bg-hover);
}

.system-body {
  padding: var(--spacing-sm);
  max-height: 400px;
  overflow-y: auto;
}

.system-body.body-expanded {
  max-height: none;
}

.system-block-item {
  margin-bottom: var(--spacing-sm);
}

.system-block-item:last-child {
  margin-bottom: 0;
}

.cache-label {
  font-size: var(--font-size-xs);
  color: var(--warning);
  font-style: italic;
  margin-bottom: 2px;
}

.system-text {
  font-size: var(--font-size-sm);
  color: var(--text);
  white-space: pre-wrap;
  word-wrap: break-word;
  line-height: 1.6;
}

:deep(.search-highlight) {
  background: var(--warning);
  color: var(--bg);
  padding: 0 2px;
}
</style>

// ui-v4/src/components/detail/blocks/SystemMessage.tsx
import { useState } from "react"

import type { SystemBlock } from "@/types"

import { UnifiedLineDiff } from "@/components/detail/diff/UnifiedLineDiff"
import { diffLinesRich } from "@/lib/diff/block-diff"

type SystemValue = string | Array<SystemBlock>
type ViewMode = "original" | "rewritten" | "diff"

interface SystemMessageProps {
  system: SystemValue
  rewrittenSystem?: SystemValue | null
}

function systemToText(system: SystemValue): string {
  if (typeof system === "string") return system
  return system.map((b) => b.text).join("\n")
}

function toBlocks(system: SystemValue): Array<SystemBlock> {
  if (typeof system === "string") return [{ type: "text", text: system }]
  return system
}

/** One block of a system payload, with `text[i]` + `[cache: type]` labels when relevant. */
function SystemBlocksBody({ blocks }: { blocks: Array<SystemBlock> }) {
  const multiple = blocks.length > 1
  return (
    <div>
      {blocks.map((block, i) => (
        <div
          key={i}
          className={multiple ? "mb-2 border border-[var(--color-border)] p-1.5 last:mb-0" : ""}
        >
          {multiple || block.cache_control ?
            <div className="mono mb-1 flex items-center gap-2 text-[11px] text-[var(--color-muted)]">
              {multiple ?
                <span>text[{i}]</span>
              : null}
              {block.cache_control ?
                <span className="italic text-[var(--color-warn)]">[cache: {block.cache_control.type}]</span>
              : null}
            </div>
          : null}
          <pre className="mono whitespace-pre-wrap break-words text-[13px] text-[var(--color-text)]">{block.text}</pre>
        </div>
      ))}
    </div>
  )
}

const TOGGLE_BASE = "mono border border-[var(--color-border)] px-2 py-0.5 text-[12px]"

function modeClass(active: boolean): string {
  return `${TOGGLE_BASE} ${active ? "text-[var(--color-primary)]" : "text-[var(--color-muted)]"}`
}

/** `modified` when content actually changed, else `rewritten` when a rewrite exists. */
function RewriteBadge({ hasRewrite, contentDiffers }: { hasRewrite: boolean; contentDiffers: boolean }) {
  if (contentDiffers) return <span className="mono text-[11px] text-[var(--color-warn)]">modified</span>
  if (hasRewrite) return <span className="mono text-[11px] text-[var(--color-muted)]">rewritten</span>
  return null
}

interface SystemBodyProps {
  mode: ViewMode
  hasRewrite: boolean
  originalBlocks: Array<SystemBlock>
  rewrittenBlocks: Array<SystemBlock>
  originalText: string
  rewrittenText: string
}

function SystemBody({ mode, hasRewrite, originalBlocks, rewrittenBlocks, originalText, rewrittenText }: SystemBodyProps) {
  if (!hasRewrite || mode === "original") return <SystemBlocksBody blocks={originalBlocks} />
  if (mode === "rewritten") return <SystemBlocksBody blocks={rewrittenBlocks} />
  return (
    <>
      {originalBlocks.length !== rewrittenBlocks.length ?
        <div className="mono mb-1 text-[11px] font-semibold text-[var(--color-warn)]">
          Block count changed: {originalBlocks.length} → {rewrittenBlocks.length}
        </div>
      : null}
      <UnifiedLineDiff rows={diffLinesRich(originalText, rewrittenText)} />
    </>
  )
}

export function SystemMessage({ system, rewrittenSystem }: SystemMessageProps) {
  const [collapsed, setCollapsed] = useState(false)
  const [mode, setMode] = useState<ViewMode>("original")

  const originalText = systemToText(system)
  const rewrittenText = rewrittenSystem ? systemToText(rewrittenSystem) : ""
  const hasRewrite = Boolean(rewrittenSystem)
  const contentDiffers = hasRewrite && originalText !== rewrittenText

  const originalBlocks = toBlocks(system)
  const rewrittenBlocks = rewrittenSystem ? toBlocks(rewrittenSystem) : []
  const hasCacheControl = originalBlocks.some((b) => b.cache_control)

  return (
    <div className="mb-2 border border-[var(--color-border)]">
      <div className="flex items-center justify-between bg-[#161616] px-2 py-1">
        <div className="flex min-w-0 items-center gap-2">
          <button
            type="button"
            onClick={() => setCollapsed((v) => !v)}
            className="select-none text-[10px] text-[var(--color-muted)]"
            aria-label={collapsed ? "Expand system" : "Collapse system"}
          >
            {collapsed ? "▸" : "▾"}
          </button>
          <span className="mono text-[11px] uppercase tracking-wider text-[var(--color-muted)]">system</span>
          {hasCacheControl ?
            <span className="mono text-[11px] text-[var(--color-warn)]">cached</span>
          : null}
          <RewriteBadge
            hasRewrite={hasRewrite}
            contentDiffers={contentDiffers}
          />
        </div>
        {hasRewrite && !collapsed ?
          <div className="flex items-center gap-1">
            <button
              type="button"
              onClick={() => setMode("original")}
              className={modeClass(mode === "original")}
            >
              Original
            </button>
            <button
              type="button"
              onClick={() => setMode("rewritten")}
              className={modeClass(mode === "rewritten")}
            >
              Rewritten
            </button>
            <button
              type="button"
              onClick={() => setMode("diff")}
              className={modeClass(mode === "diff")}
            >
              Diff
            </button>
          </div>
        : null}
      </div>

      {collapsed ? null : (
        <div className="px-2 py-1.5">
          <SystemBody
            mode={mode}
            hasRewrite={hasRewrite}
            originalBlocks={originalBlocks}
            rewrittenBlocks={rewrittenBlocks}
            originalText={originalText}
            rewrittenText={rewrittenText}
          />
        </div>
      )}
    </div>
  )
}
