// ui-v4/src/components/models/detail-tabs/LimitsVisionTab.tsx
import type { Model } from "~backend/lib/models/client"

import {
  //
  Chip,
  renderValue,
  Row,
  Section,
} from "@/components/models/detail-tabs/DetailParts"

/**
 * Limits + Vision tab. Reads raw `capabilities.limits` (exact integers, not the
 * compacted table view). The Vision block is CONDITIONAL — rendered only when
 * `capabilities.limits.vision` exists (these fields are not on DerivedCapabilities;
 * read straight from raw).
 */
export function LimitsVisionTab({ model }: { model: Model }) {
  const limits = model.capabilities?.limits
  const vision = limits?.vision

  return (
    <div>
      <Section title="Token limits">
        <Row
          label="max_context_window_tokens"
          value={limits?.max_context_window_tokens}
        />
        <Row
          label="max_prompt_tokens"
          value={limits?.max_prompt_tokens}
        />
        <Row
          label="max_output_tokens"
          value={limits?.max_output_tokens}
        />
        <Row
          label="max_non_streaming_output_tokens"
          value={limits?.max_non_streaming_output_tokens}
        />
        <Row
          label="max_inputs"
          value={limits?.max_inputs}
        />
      </Section>

      {vision ?
        <Section title="Vision">
          <Row
            label="max_prompt_images"
            value={vision.max_prompt_images}
          />
          <Row
            label="max_prompt_image_size"
            value={vision.max_prompt_image_size}
          />
          <Row label="supported_media_types">
            {vision.supported_media_types && vision.supported_media_types.length > 0 ?
              vision.supported_media_types.map((t) => <Chip key={t}>{t}</Chip>)
            : renderValue(undefined)}
          </Row>
        </Section>
      : null}
    </div>
  )
}

// ui/src/components/models/detail/tabs/LimitsVisionTab.vue
<script setup lang="ts">
import type { DerivedCapabilities } from "~backend/lib/models/capabilities"
import type { Model } from "~backend/lib/models/client"

import { computed } from "vue"

import { formatNumber } from "@/utils/formatters"

import DetailKeyValueList from "../DetailKeyValueList.vue"
import DetailSection from "../DetailSection.vue"

const props = defineProps<{ model: Model; caps: DerivedCapabilities }>()

const n = (v: number | undefined): string | null => (typeof v === "number" ? formatNumber(v) : null)

const limitRows = computed<Array<[string, string | null]>>(() => {
  const limits = props.model.capabilities?.limits
  return [
    ["Context window", n(limits?.max_context_window_tokens)],
    ["Max prompt", n(limits?.max_prompt_tokens)],
    ["Max output", n(limits?.max_output_tokens)],
    ["Non-stream output", n(limits?.max_non_streaming_output_tokens)],
    ["Max inputs", n(limits?.max_inputs)],
  ]
})

const vision = computed(() => props.model.capabilities?.limits?.vision ?? null)
const visionRows = computed<Array<[string, string | null]>>(() => {
  const v = vision.value
  if (!v) return []
  return [
    ["Max images", n(v.max_prompt_images)],
    ["Max image size", n(v.max_prompt_image_size)],
    ["Media types", v.supported_media_types?.length ? v.supported_media_types.join(", ") : null],
  ]
})
</script>

<template>
  <div>
    <DetailSection title="Limits">
      <DetailKeyValueList :rows="limitRows" />
    </DetailSection>
    <DetailSection
      v-if="vision"
      title="Vision"
    >
      <DetailKeyValueList :rows="visionRows" />
    </DetailSection>
  </div>
</template>
