// ui-v4/src/components/models/detail-tabs/OverviewTab.tsx
import type { Model } from "~backend/lib/models/client"

import { getEffectiveEndpoints } from "~backend/lib/models/endpoint"

import {
  //
  Chip,
  renderValue,
  Row,
  Section,
} from "@/components/models/detail-tabs/DetailParts"

/**
 * Overview tab: identity + picker/default flags + effective endpoints.
 *
 * Endpoints fold in here (spec §6, no separate tab). `getEffectiveEndpoints`
 * returns `supported_endpoints` verbatim when present, else infers from
 * `capabilities.type` for legacy models — inferred lists are tagged `(inferred)`
 * so an upstream-declared endpoint is distinguishable from a frontend guess.
 */
export function OverviewTab({ model }: { model: Model }) {
  const endpoints = getEffectiveEndpoints(model)
  const inferred = !model.supported_endpoints

  return (
    <div>
      <Section title="Identity">
        <Row
          label="id"
          value={model.id}
        />
        <Row
          label="name"
          value={model.name}
        />
        <Row
          label="vendor"
          value={model.vendor}
        />
        <Row
          label="version"
          value={model.version}
        />
        <Row
          label="family"
          value={model.capabilities?.family}
        />
        <Row
          label="tokenizer"
          value={model.capabilities?.tokenizer}
        />
        <Row
          label="type"
          value={model.capabilities?.type}
        />
        <Row
          label="object"
          value={model.capabilities?.object}
        />
      </Section>

      <Section title="Picker & defaults">
        <Row
          label="model_picker_category"
          value={model.model_picker_category}
        />
        <Row
          label="model_picker_enabled"
          value={model.model_picker_enabled}
        />
        <Row
          label="is_chat_default"
          value={model.is_chat_default}
        />
        <Row
          label="is_chat_fallback"
          value={model.is_chat_fallback}
        />
        <Row
          label="preview"
          value={model.preview}
        />
      </Section>

      <Section title="Endpoints">
        <Row label={inferred ? "endpoints (inferred)" : "endpoints"}>
          {endpoints && endpoints.length > 0 ?
            <span>
              {endpoints.map((e) => (
                <Chip key={e}>{e}</Chip>
              ))}
              {inferred ?
                <span className="ml-1 text-[10px] text-[var(--content-muted)]">inferred from capabilities.type</span>
              : null}
            </span>
          : renderValue(undefined)}
        </Row>
      </Section>
    </div>
  )
}

// ui/src/components/models/detail/tabs/OverviewTab.vue
<script setup lang="ts">
import type { DerivedCapabilities } from "~backend/lib/models/capabilities"
import type { Model } from "~backend/lib/models/client"

import { computed } from "vue"

import { getEffectiveEndpoints } from "@/utils/model-endpoints"

import DetailKeyValueList from "../DetailKeyValueList.vue"
import DetailSection from "../DetailSection.vue"

const props = defineProps<{ model: Model; caps: DerivedCapabilities }>()

const rows = computed<Array<[string, string | null]>>(() => [
  ["Name", props.model.name ?? null],
  ["Vendor", props.model.vendor ?? null],
  ["Version", props.model.version ?? null],
  ["Family", props.model.capabilities?.family ?? null],
  ["Tokenizer", props.model.capabilities?.tokenizer ?? null],
  ["Type", props.model.capabilities?.type ?? null],
  ["Object", props.model.capabilities?.object ?? null],
  ["Category", props.model.model_picker_category ?? null],
  ["Picker enabled", String(props.model.model_picker_enabled)],
  ["Chat default", String(props.model.is_chat_default)],
  ["Chat fallback", String(props.model.is_chat_fallback)],
  ["Preview", String(props.model.preview)],
])

const endpoints = computed(() => getEffectiveEndpoints(props.model))
const isInferred = computed(() => !props.model.supported_endpoints)
</script>

<template>
  <div>
    <DetailSection title="Overview">
      <DetailKeyValueList :rows="rows" />
    </DetailSection>
    <DetailSection title="Endpoints">
      <div
        v-if="endpoints.length === 0"
        class="text-medium-emphasis text-caption"
      >
        —
      </div>
      <div
        v-else
        class="endpoint-chips"
      >
        <v-chip
          v-for="ep in endpoints"
          :key="ep"
          size="x-small"
          variant="tonal"
        >
          {{ ep
          }}<span
            v-if="isInferred"
            class="inferred"
          >
            (inferred)</span
          >
        </v-chip>
      </div>
    </DetailSection>
  </div>
</template>

<style scoped>
.endpoint-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.inferred {
  opacity: 0.6;
  font-style: italic;
}
</style>
