// ui-v4/src/components/models/detail-tabs/TelemetryTab.tsx
import type {
  //
  JoinedModelTelemetry,
  ModelTelemetryStats,
} from "@/lib/model-telemetry"

import {
  //
  renderValue,
  Row,
  Section,
} from "@/components/models/detail-tabs/DetailParts"
import { formatDuration } from "@/lib/format"

/** Render one telemetry window (7d or since-start), or a "no traffic" note when absent. */
function Window({ title, stats }: { title: string; stats: ModelTelemetryStats | null }) {
  if (!stats) {
    return (
      <Section title={title}>
        <div className="py-0.5 text-[12px] text-[#555]">no traffic</div>
      </Section>
    )
  }
  const u = stats.usage
  return (
    <Section title={title}>
      <Row
        label="requests"
        value={stats.requestCount}
      />
      <Row
        label="success"
        value={stats.successCount}
      />
      <Row label="failure">
        <span className={stats.failureCount > 0 ? "text-[var(--color-fail)]" : undefined}>{stats.failureCount}</span>
      </Row>
      <Row
        label="avg duration"
        value={formatDuration(stats.averageDurationMs)}
      />
      <Row
        label="input tokens"
        value={u.inputTokens}
      />
      <Row
        label="output tokens"
        value={u.outputTokens}
      />
      <Row
        label="total tokens"
        value={u.totalTokens}
      />
      <Row
        label="cache read tokens"
        value={u.cacheReadInputTokens}
      />
      <Row
        label="cache creation tokens"
        value={u.cacheCreationInputTokens}
      />
      <Row
        label="reasoning tokens"
        value={u.reasoningTokens}
      />
    </Section>
  )
}

/**
 * Telemetry tab: runtime request telemetry joined by normalized model id (spec §4).
 *
 * Both windows shown: `Last 7 days` (primary) + `Since start` (cumulative). All
 * 6 token components are surfaced. The failure count aggregates by upstream
 * canonical name, so pure-alias failing requests (no success leg to backfill the
 * canonical id) land in the page's "Unmatched telemetry" section rather than
 * here — annotated below so a low failure count isn't misread.
 */
export function TelemetryTab({ telemetry }: { telemetry: JoinedModelTelemetry | null }) {
  if (!telemetry || (!telemetry.last7d && !telemetry.sinceStart)) {
    return (
      <div>
        <div className="py-0.5 text-[12px] text-[#888]">{renderValue(undefined)} no runtime telemetry joined to this model.</div>
        <p className="mt-2 text-[11px] leading-relaxed text-[var(--color-muted)]">
          Failure counts aggregate by upstream canonical name; pure-alias failing requests appear in the page's Unmatched telemetry section.
        </p>
      </div>
    )
  }
  return (
    <div>
      <Window
        title="Last 7 days"
        stats={telemetry.last7d}
      />
      <Window
        title="Since start"
        stats={telemetry.sinceStart}
      />
      <p className="mt-2 text-[11px] leading-relaxed text-[var(--color-muted)]">
        Failure counts aggregate by upstream canonical name; pure-alias failing requests appear in the page's Unmatched telemetry section.
      </p>
    </div>
  )
}

// ui/src/components/models/detail/tabs/TelemetryTab.vue
<script setup lang="ts">
import type { DerivedCapabilities } from "~backend/lib/models/capabilities"
import type { Model } from "~backend/lib/models/client"
import type { JoinedModelTelemetry } from "@/composables/model-telemetry-join"
import type { RequestTelemetryModelStats } from "@/composables/telemetry-parse"

import { computed } from "vue"

import { formatDuration, formatNumber } from "@/utils/formatters"

import DetailKeyValueList from "../DetailKeyValueList.vue"
import DetailSection from "../DetailSection.vue"

const props = defineProps<{ model: Model; caps: DerivedCapabilities; telemetry: JoinedModelTelemetry | null }>()

const last7d = computed(() => props.telemetry?.last7d ?? null)
const sinceStart = computed(() => props.telemetry?.sinceStart ?? null)
const hasTraffic = computed(() => Boolean(last7d.value || sinceStart.value))

function statRows(stats: RequestTelemetryModelStats): Array<[string, string | null]> {
  return [
    ["Requests", formatNumber(stats.requestCount)],
    ["Success", formatNumber(stats.successCount)],
    ["Failure", formatNumber(stats.failureCount)],
    ["Avg duration", formatDuration(stats.averageDurationMs)],
    ["Input tokens", formatNumber(stats.usage.inputTokens)],
    ["Output tokens", formatNumber(stats.usage.outputTokens)],
    ["Total tokens", formatNumber(stats.usage.totalTokens)],
    ["Cache read tokens", formatNumber(stats.usage.cacheReadInputTokens)],
    ["Cache creation tokens", formatNumber(stats.usage.cacheCreationInputTokens)],
    ["Reasoning tokens", formatNumber(stats.usage.reasoningTokens)],
  ]
}

const last7dRows = computed(() => (last7d.value ? statRows(last7d.value) : []))
const sinceStartRows = computed(() => (sinceStart.value ? statRows(sinceStart.value) : []))
</script>

<template>
  <div>
    <div
      v-if="!hasTraffic"
      class="no-traffic text-medium-emphasis"
    >
      No traffic recorded for this model.
    </div>
    <template v-else>
      <DetailSection
        v-if="last7d"
        title="Last 7 days"
      >
        <DetailKeyValueList :rows="last7dRows" />
      </DetailSection>
      <DetailSection
        v-if="sinceStart"
        title="Since start"
      >
        <DetailKeyValueList :rows="sinceStartRows" />
      </DetailSection>
    </template>
    <div class="telemetry-note text-caption text-medium-emphasis">
      Failure counts are aggregated by upstream canonical name; pure-alias failed requests appear in the "Unmatched telemetry" section.
    </div>
  </div>
</template>

<style scoped>
.no-traffic {
  padding: 16px 0;
  font-size: 0.9rem;
}

.telemetry-note {
  margin-top: 10px;
  line-height: 1.4;
}
</style>
