// ui/src/components/models/ModelsColumnMenu.vue
<script setup lang="ts">
import type { UseModelColumnsReturn } from "@/composables/useModelColumns"

const props = defineProps<{ columns: UseModelColumnsReturn }>()
</script>

<template>
  <v-menu :close-on-content-click="false">
    <template #activator="{ props: menuProps }">
      <v-btn
        v-bind="menuProps"
        variant="outlined"
        size="small"
        prepend-icon="mdi-view-column"
      >
        Columns
      </v-btn>
    </template>

    <div class="column-menu">
      <div class="menu-head">
        <span class="menu-title">Columns</span>
        <button
          type="button"
          data-testid="columns-reset"
          class="reset-btn"
          @click="props.columns.reset()"
        >
          Reset
        </button>
      </div>
      <label
        v-for="col in props.columns.ALL_COLUMNS"
        :key="col.key"
        class="menu-row"
      >
        <input
          type="checkbox"
          :data-col="col.key"
          :checked="props.columns.isVisible(col.key)"
          @change="props.columns.toggle(col.key)"
        />
        <span>{{ col.label }}</span>
      </label>
    </div>
  </v-menu>
</template>

<style scoped>
.column-menu {
  background: rgb(var(--v-theme-surface));
  border: 1px solid rgb(var(--v-theme-surface-variant));
  padding: 10px 12px;
  min-width: 200px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.menu-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-bottom: 6px;
  border-bottom: 1px solid rgb(var(--v-theme-surface-variant));
  margin-bottom: 4px;
}

.menu-title {
  font-size: 0.72rem;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: rgb(var(--v-theme-secondary));
  font-weight: 700;
}

.reset-btn {
  font-size: 0.72rem;
  color: rgb(var(--v-theme-primary));
  cursor: pointer;
}

.menu-row {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 0.83rem;
  cursor: pointer;
}
</style>

// ui-v4/src/components/models/ModelsColumnMenu.tsx
import {
  //
  MODEL_COLUMNS,
  type ModelColumnKey,
  type ModelColumnVisibility,
} from "@/lib/model-columns"

interface ModelsColumnMenuProps {
  columns: ModelColumnVisibility
  onToggle: (key: ModelColumnKey) => void
  onReset: () => void
}

export function ModelsColumnMenu({ columns, onToggle, onReset }: ModelsColumnMenuProps) {
  return (
    <details className="relative">
      <summary className="mono cursor-pointer list-none border border-[var(--color-border)] px-2 py-1 text-[12px] text-[var(--color-text)] hover:text-[var(--color-primary)]">
        Columns
      </summary>
      <div className="absolute right-0 z-10 mt-1 min-w-[180px] border border-[var(--color-border)] bg-[var(--color-surface)] p-2">
        <div className="mb-1 flex items-center justify-between border-b border-[var(--color-border)] pb-1">
          <span className="text-[11px] uppercase tracking-wider text-[var(--color-muted)]">Columns</span>
          <button
            type="button"
            className="text-[11px] text-[var(--color-primary)]"
            onClick={onReset}
          >
            Reset
          </button>
        </div>
        {MODEL_COLUMNS.map((col) => (
          <label
            key={col.key}
            className="flex cursor-pointer items-center gap-2 py-0.5 text-[12px]"
          >
            <input
              type="checkbox"
              data-col={col.key}
              checked={columns[col.key]}
              onChange={() => onToggle(col.key)}
            />
            <span>{col.label}</span>
          </label>
        ))}
      </div>
    </details>
  )
}
