// ui/history-v3/src/components/message/ContentRenderer.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ContentBlock, MessageContent } from '@/types'
import {
  isTextBlock,
  isThinkingBlock,
  isRedactedThinkingBlock,
  isToolUseBlock,
  isToolResultBlock,
  isImageBlock,
  normalizeToContentBlocks,
} from '@/utils/typeGuards'
import { useContentContext } from '@/composables/useContentContext'
import TextBlock from './TextBlock.vue'
import ThinkingBlock from './ThinkingBlock.vue'
import ImageBlock from './ImageBlock.vue'
import ToolUseBlock from './ToolUseBlock.vue'
import ToolResultBlock from './ToolResultBlock.vue'
import GenericBlock from './GenericBlock.vue'
import ErrorBoundary from '@/components/ui/ErrorBoundary.vue'

const props = defineProps<{
  content: string | ContentBlock[]
  /** Full message object — enables OpenAI tool_calls rendering */
  message?: MessageContent
}>()

const { filterType, toolUseNameMap } = useContentContext()

const blocks = computed<ContentBlock[]>(() => {
  // If full message is provided, use the normalizer (handles both Anthropic and OpenAI formats)
  if (props.message) {
    return normalizeToContentBlocks(props.message)
  }
  // Fallback: content-only mode (backward compatible)
  if (typeof props.content === 'string') {
    return [{ type: 'text', text: props.content }]
  }
  if (!Array.isArray(props.content)) return []
  return props.content
})

const filteredBlocks = computed(() => {
  let result = blocks.value

  // Type filter
  if (filterType.value) {
    result = result.filter(b => b.type === filterType.value)
  }

  return result
})
</script>

<template>
  <div class="content-renderer">
    <template v-for="(block, i) in filteredBlocks" :key="i">
      <ErrorBoundary :label="block.type + ' block'">
        <TextBlock
          v-if="isTextBlock(block)"
          :text="block.text"
        />
        <ThinkingBlock
          v-else-if="isThinkingBlock(block)"
          :text="block.thinking"
        />
        <ThinkingBlock
          v-else-if="isRedactedThinkingBlock(block)"
          text=""
          :redacted="true"
        />
        <ImageBlock
          v-else-if="isImageBlock(block) && block.source.type === 'base64'"
          :media-type="block.source.media_type"
          :data="block.source.data"
        />
        <ToolUseBlock
          v-else-if="isToolUseBlock(block)"
          :block="block"
        />
        <ToolResultBlock
          v-else-if="isToolResultBlock(block)"
          :block="block"
          :tool-name="toolUseNameMap[block.tool_use_id]"
        />
        <GenericBlock
          v-else
          :block="block"
        />
      </ErrorBoundary>
    </template>
  </div>
</template>

<style scoped>
.content-renderer {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
}

</style>

// ui-v4/src/components/detail/ContentRenderer.tsx
import type { ContentBlock } from "@/lib/content/types"

import { GenericBlock } from "@/components/detail/blocks/GenericBlock"
import { ImageBlock } from "@/components/detail/blocks/ImageBlock"
import { TextBlock } from "@/components/detail/blocks/TextBlock"
import { ThinkingBlock } from "@/components/detail/blocks/ThinkingBlock"
import { ToolResultBlock } from "@/components/detail/blocks/ToolResultBlock"
import { ToolUseBlock } from "@/components/detail/blocks/ToolUseBlock"
import { ErrorBoundary } from "@/components/detail/ErrorBoundary"
import {
  //
  isImageBlock,
  isRedactedThinkingBlock,
  isTextBlock,
  isThinkingBlock,
  isToolResultBlock,
  isToolUseBlock,
} from "@/lib/content/normalize"

function renderBlock(block: ContentBlock) {
  if (isTextBlock(block)) return <TextBlock block={block} />
  if (isThinkingBlock(block)) return <ThinkingBlock block={block} />
  if (isRedactedThinkingBlock(block))
    return (
      <ThinkingBlock
        block={block}
        redacted
      />
    )
  if (isToolUseBlock(block)) return <ToolUseBlock block={block} />
  if (isToolResultBlock(block)) return <ToolResultBlock block={block} />
  if (isImageBlock(block)) return <ImageBlock block={block} />
  return <GenericBlock block={block} />
}

/** 纯分发器 —— 按 block.type 选组件(spec §9,8 类 + generic),每块包 ErrorBoundary。 */
export function ContentRenderer({ blocks }: { blocks: Array<ContentBlock> }) {
  return (
    <div className="flex flex-col gap-1">
      {blocks.map((block, i) => (
        <ErrorBoundary
          key={i}
          label={block.type}
        >
          {renderBlock(block)}
        </ErrorBoundary>
      ))}
    </div>
  )
}
