// ui-v4/src/components/models/ModelsTable.tsx
import type { DerivedCapabilities } from "~backend/lib/models/capabilities"
import type { Model } from "~backend/lib/models/client"

import { deriveCapabilities } from "~backend/lib/models/capabilities"
import { useMemo } from "react"

import type {
  //
  ModelColumnKey,
  ModelColumnVisibility,
} from "@/lib/model-columns"
import type { ModelSortKey } from "@/lib/model-filters"
import type { JoinedModelTelemetry } from "@/lib/model-telemetry"

import { formatNumber } from "@/lib/format"

const CAP_COLS: ReadonlyArray<{ key: ModelColumnKey; deriveKey: keyof DerivedCapabilities; label: string }> = [
  { key: "vision", deriveKey: "vision", label: "Vis" },
  { key: "toolCalls", deriveKey: "toolCalls", label: "Tool" },
  { key: "parallelToolCalls", deriveKey: "parallelToolCalls", label: "Par" },
  { key: "structuredOutputs", deriveKey: "structuredOutputs", label: "Struct" },
  { key: "streaming", deriveKey: "streaming", label: "Strm" },
  { key: "thinking", deriveKey: "thinking", label: "Think" },
]

interface ModelsTableProps {
  models: Array<Model>
  columns: ModelColumnVisibility
  telemetryFor: (id: string) => JoinedModelTelemetry | null
  maxRequests7d: number
  sortKey: ModelSortKey
  sortDesc: boolean
  onSort: (key: ModelSortKey) => void
  selectedId?: string | null
  onSelect?: (id: string) => void
}

const HEAD = "px-2 py-1 text-left text-[11px] uppercase tracking-wider text-[var(--color-muted)]"

export function ModelsTable({ models, columns, telemetryFor, maxRequests7d, sortKey, sortDesc, onSort, selectedId, onSelect }: ModelsTableProps) {
  const capsById = useMemo(() => {
    const map = new Map<string, DerivedCapabilities>()
    for (const m of models) map.set(m.id, deriveCapabilities(m))
    return map
  }, [models])

  const caret = (key: ModelSortKey) =>
    sortKey === key ?
      sortDesc ? " ▼"
      : " ▲"
    : ""
  const sortable = (key: ModelSortKey, label: string, extra = "") => (
    <th
      className={`${HEAD} cursor-pointer select-none hover:text-[var(--color-primary)] ${extra}`}
      onClick={() => onSort(key)}
    >
      {label}
      {caret(key)}
    </th>
  )

  return (
    <table className="mono w-full text-[12px]">
      <thead className="sticky top-0 z-[1] bg-[var(--color-bg)]">
        <tr>
          {sortable("id", "Model")}
          {columns.vendor ? sortable("vendor", "Vendor") : null}
          {columns.context ? sortable("context", "Ctx", "text-right") : null}
          {columns.output ? sortable("output", "Out", "text-right") : null}
          {columns.effort ?
            <th className={`${HEAD} text-right`}>Effort</th>
          : null}
          {CAP_COLS.map((c) =>
            columns[c.key] ?
              <th
                key={c.key}
                className={`${HEAD} text-center`}
              >
                {c.label}
              </th>
            : null,
          )}
          {columns.billing ? sortable("billing", "$×", "text-right") : null}
          {columns.requests7d ? sortable("requests7d", "Req 7d", "text-right") : null}
        </tr>
      </thead>
      <tbody>
        {models.map((m) => {
          const caps = capsById.get(m.id)!
          const req = telemetryFor(m.id)?.last7d?.requestCount ?? 0
          const selected = m.id === selectedId
          return (
            <tr
              key={m.id}
              className={`border-b border-[#1e1e24] ${onSelect ? "cursor-pointer hover:bg-[#1a1a20]" : ""} ${selected ? "border-l-2 border-l-[var(--color-primary)] bg-[#3a2f1a]" : ""}`}
              aria-selected={selected}
              onClick={onSelect ? () => onSelect(m.id) : undefined}
            >
              <td className="px-2 py-1 text-[var(--color-primary)]">
                {m.id}
                {m.is_chat_default ?
                  <span className="ml-1 text-[10px] text-[var(--color-muted)]">default</span>
                : null}
                {m.preview ?
                  <span className="ml-1 text-[10px] text-[var(--color-muted)]">preview</span>
                : null}
              </td>
              {columns.vendor ?
                <td className="px-2 py-1 text-[#aaa]">{m.vendor}</td>
              : null}
              {columns.context ?
                <td className="px-2 py-1 text-right text-[#cdb]">{formatNumber(caps.contextWindow)}</td>
              : null}
              {columns.output ?
                <td className="px-2 py-1 text-right text-[#cdb]">{formatNumber(caps.maxOutput)}</td>
              : null}
              {columns.effort ?
                <td className="px-2 py-1 text-right text-[var(--color-muted)]">{caps.reasoningEffort.join("/") || "-"}</td>
              : null}
              {CAP_COLS.map((c) =>
                columns[c.key] ?
                  <td
                    key={c.key}
                    className="px-2 py-1 text-center"
                  >
                    {caps[c.deriveKey] ?
                      <span className="text-[var(--color-ok)]">✓</span>
                    : <span className="text-[#3a3a42]">·</span>}
                  </td>
                : null,
              )}
              {columns.billing ?
                <td className="px-2 py-1 text-right text-[#cdb]">{m.billing?.multiplier ?? "-"}</td>
              : null}
              {columns.requests7d ?
                <td className="relative px-2 py-1 text-right text-[#cdb]">
                  {req || "-"}
                  {req > 0 ?
                    <span
                      className="absolute bottom-0 left-0 h-[2px] bg-[var(--color-primary)] opacity-60"
                      style={{ width: `${maxRequests7d > 0 ? (req / maxRequests7d) * 100 : 0}%` }}
                    />
                  : null}
                </td>
              : null}
            </tr>
          )
        })}
      </tbody>
    </table>
  )
}

// ui/src/components/models/ModelsTable.vue
<script setup lang="ts">
import type { DerivedCapabilities } from "~backend/lib/models/capabilities"
import type { Model } from "~backend/lib/models/client"

import {
  //
  computed,
  ref,
} from "vue"

import type { JoinedModelTelemetry } from "@/composables/model-telemetry-join"
import type {
  //
  ModelColumnKey,
  UseModelColumnsReturn,
} from "@/composables/useModelColumns"

const props = defineProps<{
  models: Array<Model>
  caps: (m: Model) => DerivedCapabilities
  vendorColor: (v: string | undefined) => string
  fmtNum: (n: number | undefined) => string
  selectedId?: string | null
  columns?: UseModelColumnsReturn
  telemetryFor?: (id: string) => JoinedModelTelemetry | null
  maxRequests7d?: number
}>()

const emit = defineEmits<{ select: [string] }>()

/** Column is shown when no column controller is provided (standalone), or the controller says so. */
function showCol(key: ModelColumnKey): boolean {
  return props.columns?.isVisible(key) ?? true
}

function requests7d(m: Model): number {
  return props.telemetryFor?.(m.id)?.last7d?.requestCount ?? 0
}

function requestShare(m: Model): number {
  const max = props.maxRequests7d ?? 0
  return max > 0 ? (requests7d(m) / max) * 100 : 0
}

type SortKey = "id" | "vendor" | "context" | "output" | "billing"
const sortKey = ref<SortKey>("id")
const sortDesc = ref(false)

function sortVal(m: Model, key: SortKey): string | number {
  const c = props.caps(m)
  switch (key) {
    case "id": {
      return m.id
    }
    case "vendor": {
      return m.vendor ?? ""
    }
    case "context": {
      return c.contextWindow ?? 0
    }
    case "output": {
      return c.maxOutput ?? 0
    }
    case "billing": {
      return m.billing?.multiplier ?? 0
    }
    default: {
      return ""
    }
  }
}

const sorted = computed(() => {
  const list = [...props.models]
  list.sort((a, b) => {
    const va = sortVal(a, sortKey.value)
    const vb = sortVal(b, sortKey.value)
    const cmp = typeof va === "number" && typeof vb === "number" ? va - vb : String(va).localeCompare(String(vb))
    return sortDesc.value ? -cmp : cmp
  })
  return list
})

function toggleSort(key: SortKey): void {
  if (sortKey.value === key) sortDesc.value = !sortDesc.value
  else {
    sortKey.value = key
    // Numeric columns default to descending (largest first) — more useful.
    sortDesc.value = key === "context" || key === "output" || key === "billing"
  }
}

// Capability matrix columns (icon per derived boolean) + thinking/effort detail.
const capCols: Array<{ key: keyof DerivedCapabilities; label: string }> = [
  { key: "vision", label: "Vis" },
  { key: "toolCalls", label: "Tool" },
  { key: "parallelToolCalls", label: "Par" },
  { key: "structuredOutputs", label: "Struct" },
  { key: "streaming", label: "Stream" },
  { key: "thinking", label: "Think" },
]

function thinkingDetail(c: DerivedCapabilities): string {
  if (!c.thinking) return ""
  if (c.maxThinkingBudget > 0) return `≤${props.fmtNum(c.maxThinkingBudget)}`
  return c.adaptiveThinking ? "adaptive" : ""
}
</script>

<template>
  <div class="models-table-wrap">
    <v-table
      density="compact"
      fixed-header
      hover
      class="models-table bg-transparent"
    >
      <thead>
        <tr>
          <th
            class="th-sort"
            @click="toggleSort('id')"
          >
            Model<span
              v-if="sortKey === 'id'"
              class="sort-caret"
              >{{ sortDesc ? "▼" : "▲" }}</span
            >
          </th>
          <th
            v-if="showCol('vendor')"
            class="th-sort"
            @click="toggleSort('vendor')"
          >
            Vendor<span
              v-if="sortKey === 'vendor'"
              class="sort-caret"
              >{{ sortDesc ? "▼" : "▲" }}</span
            >
          </th>
          <th
            v-if="showCol('context')"
            class="th-num th-sort"
            @click="toggleSort('context')"
          >
            Ctx<span
              v-if="sortKey === 'context'"
              class="sort-caret"
              >{{ sortDesc ? "▼" : "▲" }}</span
            >
          </th>
          <th
            v-if="showCol('output')"
            class="th-num th-sort"
            @click="toggleSort('output')"
          >
            Out<span
              v-if="sortKey === 'output'"
              class="sort-caret"
              >{{ sortDesc ? "▼" : "▲" }}</span
            >
          </th>
          <th
            v-if="showCol('effort')"
            class="th-num"
          >
            Effort
          </th>
          <th
            v-for="col in capCols"
            v-show="showCol(col.key as ModelColumnKey)"
            :key="col.key"
            class="th-cap"
          >
            {{ col.label }}
          </th>
          <th
            v-if="showCol('billing')"
            class="th-num th-sort"
            @click="toggleSort('billing')"
          >
            $×<span
              v-if="sortKey === 'billing'"
              class="sort-caret"
              >{{ sortDesc ? "▼" : "▲" }}</span
            >
          </th>
          <th
            v-if="showCol('requests7d')"
            class="th-num"
          >
            Req 7d
          </th>
        </tr>
      </thead>
      <tbody>
        <template
          v-for="m in sorted"
          :key="m.id"
        >
          <tr
            class="model-row"
            :class="{ selected: m.id === selectedId }"
            :aria-selected="m.id === selectedId"
            @click="emit('select', m.id)"
          >
            <td class="td-id font-mono">
              {{ m.id
              }}<v-chip
                v-if="m.is_chat_default"
                size="x-small"
                variant="tonal"
                color="primary"
                class="ml-1"
                >default</v-chip
              ><v-chip
                v-if="m.preview"
                size="x-small"
                variant="tonal"
                class="ml-1"
                >preview</v-chip
              >
            </td>
            <td
              v-if="showCol('vendor')"
              class="dense"
            >
              <v-chip
                size="x-small"
                variant="tonal"
                :color="vendorColor(m.vendor)"
                >{{ m.vendor }}</v-chip
              >
            </td>
            <td
              v-if="showCol('context')"
              class="td-num font-mono"
            >
              {{ fmtNum(caps(m).contextWindow) }}
            </td>
            <td
              v-if="showCol('output')"
              class="td-num font-mono"
            >
              {{ fmtNum(caps(m).maxOutput) }}
            </td>
            <td
              v-if="showCol('effort')"
              class="td-num font-mono effort-cell"
            >
              {{ caps(m).reasoningEffort.join("/") || "-" }}
            </td>
            <td
              v-for="col in capCols"
              v-show="showCol(col.key as ModelColumnKey)"
              :key="col.key"
              class="td-cap"
            >
              <span
                v-if="col.key === 'thinking' && caps(m).thinking"
                class="cap-yes font-mono"
                :title="thinkingDetail(caps(m))"
                >✓</span
              >
              <span
                v-else-if="caps(m)[col.key]"
                class="cap-yes"
                >✓</span
              >
              <span
                v-else
                class="cap-no"
                >·</span
              >
            </td>
            <td
              v-if="showCol('billing')"
              class="td-num font-mono"
            >
              {{ m.billing?.multiplier ?? "-" }}
            </td>
            <td
              v-if="showCol('requests7d')"
              class="td-num font-mono req-cell"
            >
              <span class="req-count">{{ requests7d(m) || "-" }}</span>
              <span
                v-if="requests7d(m) > 0"
                class="req-bar"
                :style="{ width: `${requestShare(m)}%` }"
              />
            </td>
          </tr>
        </template>
      </tbody>
    </v-table>
  </div>
</template>

<style scoped>
.models-table-wrap {
  overflow-x: auto;
  border: 1px solid rgb(var(--v-theme-surface-variant));
  background: rgb(var(--v-theme-surface));
}

.models-table :deep(th),
.models-table :deep(td) {
  padding: 5px 8px;
  white-space: nowrap;
}

.models-table :deep(th) {
  font-size: 0.66rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: rgb(var(--v-theme-secondary));
}

.th-sort {
  cursor: pointer;
  user-select: none;
}

.th-sort:hover {
  color: rgb(var(--v-theme-primary));
}

.sort-caret {
  margin-left: 3px;
  font-size: 0.6rem;
}

.th-num,
.td-num {
  text-align: right;
}

.th-cap,
.td-cap {
  text-align: center;
}

.dense,
.td-num,
.td-cap,
.td-id {
  font-size: 0.76rem;
}

.model-row {
  cursor: pointer;
}

.model-row.selected {
  background: rgb(var(--v-theme-surface-variant));
}

.td-id {
  font-weight: 600;
}

.effort-cell {
  color: rgb(var(--v-theme-secondary));
}

.cap-yes {
  color: rgb(var(--v-theme-success));
  font-weight: 700;
}

.cap-no {
  color: rgb(var(--v-theme-surface-variant));
}

.req-cell {
  position: relative;
}

.req-bar {
  position: absolute;
  left: 0;
  bottom: 0;
  height: 2px;
  background: rgb(var(--v-theme-primary));
  opacity: 0.6;
}
</style>
